name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Compile CSS
      - name: Compile style CSS
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: assets/scss/style.scss
          destination: style.css
          outputStyle: expanded
      - name: Compile style CSS compressed
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: assets/scss/style.scss
          destination: style.min.css
          outputStyle: compressed
      # Install SSH key
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      # Transfer file to remote server
      - name: Deploy
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "mkdir -p ${{ secrets.REMOTE_PATH_BASE }}"
          rsync -ahv --exclude-from="$GITHUB_WORKSPACE/.distignore" --delete-excluded "$GITHUB_WORKSPACE/" ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH_BASE }}
