name: Tests
on: [push, pull_request]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Code style checks for PHP
        run: |
          composer install
          composer lint-php
      - name: Code style checks for SCSS
        run: |
          npm ci
          npm run lint-scss
